version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-service
    ports:
      - "7004:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=MAIN.settings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-test
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=MAIN.settings
      - DJANGO_DEBUG=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py test --verbosity=2"
    profiles:
      - test

volumes:
  sqlite_data:
  static_volume:
  media_volume:
