# Generated by Django 5.2.7 on 2025-10-22 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('user_count', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('is_webhook_set', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('first_interaction', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Bot.telegrambot')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
                'ordering': ['-last_interaction'],
                'unique_together': {('bot', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('flow_data', models.JSONField(help_text='JSON structure defining the bot flow logic')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_command', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='Bot.telegrambot')),
            ],
            options={
                'verbose_name': 'Bot Flow',
                'verbose_name_plural': 'Bot Flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('voice', 'Voice'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact', 'Contact')], default='text', max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bot.botflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Bot.botuser')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Bot.telegrambot')),
            ],
            options={
                'verbose_name': 'Bot Message',
                'verbose_name_plural': 'Bot Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot', 'user', '-created_at'], name='Bot_botmess_bot_id_a4ba4f_idx')],
            },
        ),
    ]
