# Generated by Django 5.2.7 on 2025-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional state data for flow processing'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='user_state',
            field=models.CharField(choices=[('new', 'New User'), ('welcomed', 'Welcomed'), ('awaiting_phone', 'Awaiting Phone Number'), ('registered', 'Registered'), ('active', 'Active'), ('blocked', 'Blocked')], default='new', help_text='Current state in the bot flow', max_length=50),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='bot_type',
            field=models.CharField(choices=[('simple', 'Simple Bot'), ('registration', 'Registration Bot'), ('survey', 'Survey Bot'), ('support', 'Support Bot'), ('ecommerce', 'E-commerce Bot'), ('custom', 'Custom Bot')], default='simple', help_text='Type of bot determines the flow handling strategy', max_length=50),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='get_number_text',
            field=models.TextField(blank=True, default='Please share your phone number to continue.', help_text='Text to show when requesting phone number', null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='has_get_number',
            field=models.BooleanField(default=False, help_text='Request phone number after welcome message'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='has_welcome_message',
            field=models.BooleanField(default=True, help_text='Send welcome message on /start'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='welcome_message_text',
            field=models.TextField(blank=True, help_text='Welcome message text (supports markdown)', null=True),
        ),
    ]
