# Generated by Django 5.2.7 on 2025-10-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_botuser_state_data_botuser_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='auto_setup_webhook',
            field=models.BooleanField(default=True, help_text='Automatically setup webhook when bot is saved'),
        ),
    ]
