# Generated by Django 5.2.7 on 2025-10-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_telegrambot_auto_setup_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='after_phone_number_text',
            field=models.TextField(blank=True, default='✅ Thank you! Your phone number has been saved.', help_text='Message to show after phone number is received', null=True),
        ),
    ]
